### ISSUE TITLE
/Projects Categories

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam.io#15]
Could these have a # (of projects) aligned tot he right in the dropdown beside each category?

And, once some are slected, could the select box itself say

"All Categories" (when all are selected) and "Some Categories" when some are selected ?  (not 100% sure how I want this, but would like to know if there are better options).

**Comment by asimism** [comment]
Yes we can have number of projects beside each category. 
"All Categories" and "Some Categories" is not a good idea. personally, I don't like it.

**Comment by marcoherbst** [comment]
I think you're right, I just haven't found an example of the right way of doing it. The current method also seems a little unintuitive.

**Comment by marcoherbst** [comment]
This is good enough. Closing.
