### ISSUE TITLE
Replace Formspree with Zoho CRM Forms

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam.io#17]

**Comment by asimism** [comment]
Replaced on Home, Contacts and pricing.
Also replaced on inner pages. {where Form can be shown optionally}

**Comment by asimism** [comment]
We got the form code from Affan, he took it from zoho.
Here is the code which is in place now:
<form action='https://forms.zohopublic.com/business1274/form/ContactForm/formperma/cpbxEx6GZbNCE5RxvxY1SOXbtTs3GQhEIYGzAheVvS8/htmlRecords/submit?referrername=<referralwebsite>' name='form' id='form' method='POST' accept-charset='UTF-8' enctype='multipart/form-data' onSubmit="zf_validateandsubmitdata();">
<input type="hidden" name="zf_referrer_name" value="">
<input type="hidden" name="zf_redirect_url" value="">
<input type="hidden" name="zc_gad" value="">



	<div class="form-group">
		<input class="wpcf7-textarea form-control" type="text" maxlength="255" name="Name_First" fieldType=7 size="40" value="" placeholder="First Name" style="width:50%;float:left;"/>
		<input class="wpcf7-textarea form-control" type="text" maxlength="255" name="Name_Last" fieldType=7 value="" placeholder="Last Name" style="width:50%;"/>
	</div>


	<div class="form-group">
		<input class="wpcf7-textarea form-control" type="email" maxlength="255" name="Email" size="40" value="" placeholder="Email" fieldType=9 />
		</div>


	<div class="form-group">
		<input class="wpcf7-textarea form-control" type="tel" name="SingleLine1" size="40" value="" placeholder="Phone" fieldType=1 maxlength="255"/>
	</div>


	<div class="form-group">
		<textarea class="wpcf7-textarea form-control" cols="40" name="MultiLine" maxlength="65535" rows="10" placeholder="Message"></textarea>
	</div>
	<div class="form-group">
		<button class="wpcf7-submit btn-style" type="submit">SEND</button>
	</div>
		</form>
				<script type="text/javascript">var salesIQFieldsArray = [{"formFieldName":"Email","formFieldType":9,"salesIQFieldName":"Email"}];
function zf_validateandsubmitdata(){
var visitorinfo = {};
var elements = document.getElementById("form").elements;
for (var elmIdx = 0; elmIdx<elements.length;elmIdx++) {
var inpElem = elements[elmIdx];
var fieldLinkName = inpElem.getAttribute("name");
var fieldType = inpElem.getAttribute("fieldType");
if(fieldType==="1" || fieldType==="7" || fieldType==="9" || fieldType==="11"){
for(var idx = 0; idx < salesIQFieldsArray.length; idx++) {
var salesIQObj = salesIQFieldsArray[idx];
var zfFieldName = salesIQObj.formFieldName;
var salesIQFieldName = salesIQObj.salesIQFieldName;
if(fieldType === "1"){
if(fieldLinkName===zfFieldName){
var salesIQValue = inpElem.value;
if(salesIQFieldName==="Phone"){
visitorinfo.contactnumber = salesIQValue;
}
if(salesIQFieldName==="Name"){
visitorinfo.name = salesIQValue;
}
}
}
if(fieldType==="7"){
var zfFldCompLinkName = salesIQObj.fieldCompLinkName;
if(fieldLinkName===zfFldCompLinkName){
var salesIQValue=inpElem.value;
visitorinfo.name = salesIQValue;
}
}
if(fieldType==="9"){
if(fieldLinkName===zfFieldName){
var salesIQValue=inpElem.value;
visitorinfo.email = salesIQValue;
}
}
if(fieldType==="11"){
fieldLinkName = inpElem.getAttribute("compname");
if(fieldLinkName===zfFieldName){
var phoneFormat = inpElem.getAttribute("phoneFormat");
var salesIQValue="";
if(phoneFormat==="1"){
salesIQValue = document.getElementById("international_"+fieldLinkName+"_countrycode").value; 
var isCodeEnabled = inpElem.getAttribute("isCountryCodeEnabled");
if(isCodeEnabled === "true"&& salesIQValue != null && salesIQValue !=""){
salesIQValue = document.getElementById("international_"+fieldLinkName+"_countrycodeval").value+salesIQValue;
}
}else if(phoneFormat==="2"){
var countryCode = document.getElementById(fieldLinkName+"_countrycode").value;
var first = document.getElementById(fieldLinkName+"_first").value;
var last = document.getElementById(fieldLinkName+"_second").value;
salesIQValue =countryCode+first+last;
}
visitorinfo.contactnumber = salesIQValue;
}
}
}
}
}
parent.postMessage(JSON.stringify({ type: 'zoho.salesiq.apimessage', visitor: visitorinfo } ), '*');// No I18N
}</script>
