### ISSUE TITLE
Open Graph MetaData

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam.io#2]
https://ogp.me/

**Comment by asimism** [comment]
Please add more details

**Comment by marcoherbst** [comment]
See the link above, it explains how to use OGP. 
Then you can test your results using something like this: 
https://opengraphcheck.com/result.php?url=https%3A%2F%2Fevercam.io%2F#.XeoVYej7SUk

the idea is that when we paste a URL into, for example, FB or Whatsapp, that it knows which thumbnails and text to use.

**Comment by asimism** [comment]
All the open graph meta tags are already there in the website except the thumbnail url
![image](https://user-images.githubusercontent.com/5477165/70327548-d9e3e000-1858-11ea-91a4-3f5a3380b2db.png)
Question is what thumbnail should be used ? I think the logo on a white background ?

**Comment by marcoherbst** [comment]
Yes please

**Comment by asimism** [comment]
Added thumbnail meta data
![image](https://user-images.githubusercontent.com/5477165/70498963-e2c70100-1b39-11ea-87bb-4b89957490b3.png)
