### ISSUE TITLE
Footer Changes & Partner Changes

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam.io#4]
Remove Evercam from all 3 titles.
About
Features
Partners

Under Partners, take the text from installer opportunities and add it to the bottom of /partners
Add a link to "Approved Installers"  in footer, under Partners and link this to "/partners" page.
Add a link under Partners to "Partner Intranet" and link to /cp/ (which is currently not working, but @affan00 will fix).

**Comment by asimism** [comment]
done all tasks except the one which Affan needs to do and once he has done his part we will take it from there.

**Comment by asimism** [comment]
@affan00 Could you please explain what needs done here ? We already have done some work as per my comment above.

**Comment by marcoherbst** [comment]
![image](https://user-images.githubusercontent.com/5648894/71260289-6bac1c80-2332-11ea-8bc7-240c102ec06f.png)

Hmmm

"Remove 'Evercam' from all 3 titles.

And, the /cp/ task, please could the @asimism team take this, @affan00  is not going to get this done, I'm afraid.

**Comment by marcoherbst** [comment]
Also, please remove links to Komply and to Litterbug.

**Comment by asimism** [comment]
Removed links to Komply and to Litterbug.
