### ISSUE TITLE
Missing pages from old site

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam.io#6]
This includes the /cp/ pages please (Which are password protected)

**Comment by asimism** [comment]
Migration status can be seen on this spreadsheet https://docs.google.com/spreadsheets/d/142pDM061PMbqGPVQVDtTMFVMyhspccyUHaJTf0tjWuc/edit#gid=496060455
if you are happy then close this ticket or let me know what further needs migrated. (there are projects  which are password protected, don't know if we should migrate them)

**Comment by marcoherbst** [comment]
I am pretty sure we had more than the ones mentioned.
For example: https://oldevercam.edgecommander.com/cp/
 (which we definitely do want migrated)

My suggestion is that someone does a full comparison of both sites.
